import type { DirectorateId } from "./directorates";
import type { ArkivistReport } from "./arkivist-types";

export const ARKIVIST_PROFILE = {
  name: "Arta Krasniqi",
  role: "Arkiviste Kryesore",
  email: "arta.krniqi@gjakova.rks-gov.net",
  initials: "AK",
};

function loc(
  address: string,
  neighborhood: string,
  lat: number,
  lng: number,
) {
  return { address, neighborhood, lat, lng };
}

function ai(
  confidence: number,
  suggestedCategory: string,
  suggestedPriority: ArkivistReport["priority"],
  suggestedDirectorate: DirectorateId,
  reasoning: string,
) {
  return {
    confidence,
    suggestedCategory,
    suggestedPriority,
    suggestedDirectorate,
    reasoning,
  };
}

export const mockReports: ArkivistReport[] = [
  {
    id: "GJK-1042",
    title: "Rrjedhje e madhe e ujit",
    description:
      "Ka një rrjedhje të madhe uji pranë hyrjes së spitalit. Uji po përhapet në rrugë dhe po vështirëson qarkullimin e ambulancave. Situata ka filluar sot në mëngjes.",
    citizenNotes: "Uji po hyn edhe në trotuar. Ju lutem urgjent.",
    date: "2026-09-26",
    time: "08:42",
    createdAt: "2026-09-26T08:42:00",
    location: loc("Rr. UÇK, pranë Spitalit", "Qendër", 42.3854, 20.4276),
    category: "Ujësjellës",
    directorateId: "SHP",
    sector: "Rrjeti i ujësjellësit",
    priority: "Kritike",
    status: "NE_SHQYRTIM",
    photoUrl: "https://picsum.photos/seed/gjk1042/800/500",
    aiAnalysis: ai(
      94,
      "Ujësjellës",
      "Kritike",
      "SHP",
      "Rrjedhje aktive e ujit të pijshëm në zonë kritike (spital). Ndikim i lartë në trafik dhe shërbime emergjente. Rekomandohet Drejtoria për Shërbime Publike për izolim të valvules dhe ndërhyrje emergjente.",
    ),
    timeline: ["Raportuar", "Analizuar nga AI", "Në shqyrtim"],
    citizenName: "Qytetar anonim",
  },
  {
    id: "GJK-1031",
    title: "Gropë e rrezikshme në rrugë",
    description:
      "Gropë e madhe në mes të rrugës Nënë Tereza. Disa makina kanë dëmtuar gomat. Duhet ndërhyrje urgjente me sinjalizim dhe riparim.",
    date: "2026-09-25",
    time: "16:18",
    createdAt: "2026-09-25T16:18:00",
    location: loc("Rr. Nënë Tereza", "Qendër", 42.3801, 20.4304),
    category: "Infrastrukturë",
    directorateId: "INF",
    sector: "Mirëmbajtja e rrugëve",
    priority: "E lartë",
    status: "NE_SHQYRTIM",
    photoUrl: "https://picsum.photos/seed/gjk1031/800/500",
    aiAnalysis: ai(
      89,
      "Infrastrukturë",
      "E lartë",
      "INF",
      "Gropë e thellë në rrugë me trafik të lartë. Rrezik aksidenti dhe dëmtim automjetesh. 17 sinjale të ngjashme në zonë. Drejtoria për Infrastrukturë është përgjegjëse për asfaltim.",
    ),
    timeline: ["Raportuar", "Analizuar nga AI", "Në shqyrtim"],
    citizenName: "Mira Hoxha",
  },
  {
    id: "GJK-1047",
    title: "Ndriçim publik jashtë funksionit",
    description:
      "Shtyllat e ndriçimit në Çarshinë e Madhe nuk ndizen prej 3 netësh. Zona mbetet e errët dhe e pasigurt për këmbësorët.",
    date: "2026-09-25",
    time: "21:05",
    createdAt: "2026-09-25T21:05:00",
    location: loc("Çarshia e Madhe", "Çarshi", 42.3809, 20.4272),
    category: "Ndriçim",
    directorateId: "INF",
    sector: "Ndriçimi publik",
    priority: "Mesatare",
    status: "AI_ANALYZED",
    photoUrl: "https://picsum.photos/seed/gjk1047/800/500",
    aiAnalysis: ai(
      86,
      "Ndriçim",
      "Mesatare",
      "INF",
      "Dështim i segmentit të ndriçimit publik L-14. Afër zonës historike/turistike me trafik këmbësorësh natën.",
    ),
    timeline: ["Raportuar", "Analizuar nga AI"],
    citizenName: "Driton Berisha",
  },
  {
    id: "GJK-1019",
    title: "Deponi ilegale po zgjerohet",
    description:
      "Pranë Urës së Terzive po grumbullohen mbeturina. Deponia ilegale po zgjerohet drejt lumit dhe po bëhet e rrezikshme për mjedisin.",
    date: "2026-09-24",
    time: "11:30",
    createdAt: "2026-09-24T11:30:00",
    location: loc("Ura e Terzive, dalje jugore", "Terzi", 42.3724, 20.4308),
    category: "Mbeturina",
    directorateId: "URB",
    sector: "Menaxhimi i mbeturinave",
    priority: "E lartë",
    status: "NE_SHQYRTIM",
    photoUrl: "https://picsum.photos/seed/gjk1019/800/500",
    aiAnalysis: ai(
      91,
      "Mbeturina",
      "E lartë",
      "URB",
      "Deponi ilegale në zgjerim afër lumit. Ndikim mjedisor i lartë; 31 sinjale nga 4 lagje. Urbanizmi dhe mjedisi duhet të koordinojnë largimin.",
    ),
    timeline: ["Raportuar", "Analizuar nga AI", "Në shqyrtim"],
    citizenName: "Qytetar anonim",
  },
  {
    id: "GJK-1051",
    title: "Trotuar i dëmtuar",
    description:
      "Trotuaret në lagjen Çabrati janë të thyer dhe të rrezikshëm për të moshuarit dhe fëmijët.",
    date: "2026-09-24",
    time: "09:12",
    createdAt: "2026-09-24T09:12:00",
    location: loc("Rr. Ismail Qemali", "Çabrati", 42.3878, 20.4198),
    category: "Trotuar",
    directorateId: "INF",
    sector: "Hapësirat publike",
    priority: "Mesatare",
    status: "SUBMITTED",
    photoUrl: "https://picsum.photos/seed/gjk1051/800/500",
    aiAnalysis: ai(
      78,
      "Trotuar",
      "Mesatare",
      "INF",
      "Dëmtim i trotuarit në zonë rezidenciale. Prioritet mesatar; nuk pengon trafikun automobilistik.",
    ),
    timeline: ["Raportuar"],
    citizenName: "Valbona Gashi",
  },
  {
    id: "GJK-1028",
    title: "Sinjalizim rrugor i dëmtuar",
    description:
      "Tabela e ndalimit është e rrëzuar në kryqëzim. Ka rrezik për aksidente.",
    date: "2026-09-23",
    time: "14:45",
    createdAt: "2026-09-23T14:45:00",
    location: loc("Sheshi i Gjakovës", "Qendër", 42.3806, 20.4312),
    category: "Trafik",
    directorateId: "INF",
    sector: "Sinjalizimi rrugor",
    priority: "E lartë",
    status: "DERGUAR_TE_DREJTORIA",
    directorateStatus: "NEW",
    verifiedBy: "Arta Krasniqi",
    photoUrl: "https://picsum.photos/seed/gjk1028/800/500",
    aiAnalysis: ai(
      92,
      "Trafik",
      "E lartë",
      "INF",
      "Sinjalizim i munguar në kryqëzim me trafik të dendur. Rrezik i lartë për aksidente.",
    ),
    timeline: [
      "Raportuar",
      "Analizuar nga AI",
      "Verifikuar nga Arkivisti",
      "Dërguar te Drejtoria",
    ],
    citizenName: "Flamur Kelmendi",
  },
  {
    id: "GJK-1022",
    title: "Kontejnerë të mbushur",
    description:
      "Kontejnerët pranë Sheshit Çabrati janë plot prej 4 ditësh dhe mbeturinat po derdhen jashtë.",
    date: "2026-09-22",
    time: "07:55",
    createdAt: "2026-09-22T07:55:00",
    location: loc("Sheshi Çabrati", "Çabrati", 42.3872, 20.4205),
    category: "Mbeturina",
    directorateId: "SHP",
    sector: "Menaxhimi i mbeturinave",
    priority: "Mesatare",
    status: "DERGUAR_TE_DREJTORIA",
    directorateStatus: "IN_PROGRESS",
    verifiedBy: "Arta Krasniqi",
    photoUrl: "https://picsum.photos/seed/gjk1022/800/500",
    aiAnalysis: ai(
      88,
      "Mbeturina",
      "Mesatare",
      "SHP",
      "Mbushje e kontejnerëve mbi kapacitet në zonë publike. Ndikim higjienik dhe estetik.",
    ),
    timeline: [
      "Raportuar",
      "Analizuar nga AI",
      "Verifikuar nga Arkivisti",
      "Dërguar te Drejtoria",
      "Në proces",
    ],
    citizenName: "Qytetar anonim",
  },
  {
    id: "GJK-1060",
    title: "Kanalizim i bllokuar",
    description:
      "Uji i shiut po përmbyt bodrumin e shkollës fillore për shkak të kanalizimit të bllokuar.",
    date: "2026-09-26",
    time: "07:10",
    createdAt: "2026-09-26T07:10:00",
    location: loc("Shkolla Fillore 'Zekeria Rexha'", "Qendër", 42.3815, 20.4288),
    category: "Infrastrukturë",
    directorateId: "INF",
    sector: "Mirëmbajtja e rrugëve",
    priority: "Kritike",
    status: "DERGUAR_TE_DREJTORIA",
    directorateStatus: "NEW",
    verifiedBy: "Arta Krasniqi",
    photoUrl: "https://picsum.photos/seed/gjk1060/800/500",
    aiAnalysis: ai(
      90,
      "Infrastrukturë",
      "Kritike",
      "INF",
      "Përmbytje pranë objekti arsimor. Kërkon ndërhyrje të shpejtë nga infrastruktura.",
    ),
    timeline: [
      "Raportuar",
      "Analizuar nga AI",
      "Verifikuar nga Arkivisti",
      "Dërguar te Drejtoria",
    ],
    citizenName: "Fatmire Dreshaj",
  },
  {
    id: "GJK-1055",
    title: "Rrethojë e dëmtuar në park",
    description:
      "Rrethoja e parkut të qytetit është e thyer dhe fëmijët po dalin në rrugë.",
    date: "2026-09-21",
    time: "15:20",
    createdAt: "2026-09-21T15:20:00",
    location: loc("Parku i Qytetit", "Qendër", 42.3798, 20.4295),
    category: "Ambient",
    directorateId: "KRS",
    sector: "Hapësirat publike",
    priority: "E lartë",
    status: "DERGUAR_TE_DREJTORIA",
    directorateStatus: "RESOLVED",
    verifiedBy: "Arta Krasniqi",
    photoUrl: "https://picsum.photos/seed/gjk1055/800/500",
    aiAnalysis: ai(
      84,
      "Ambient",
      "E lartë",
      "KRS",
      "Dëmtim i infrastrukturës së parkut. Kulturë, Rini dhe Sport menaxhon hapësirat e gjelbra publike.",
    ),
    timeline: [
      "Raportuar",
      "Analizuar nga AI",
      "Verifikuar nga Arkivisti",
      "Dërguar te Drejtoria",
      "Në proces",
      "Zgjidhur",
    ],
    resolution: {
      workDescription:
        "Rrethoja u riparua me panele të reja metalike dhe u vendosën shenja paralajmëruese.",
      photoBeforeUrl: "https://picsum.photos/seed/gjk1055before/600/400",
      photoAfterUrl: "https://picsum.photos/seed/gjk1055after/600/400",
      completedAt: "2026-09-25",
    },
    citizenName: "Arben Morina",
  },
  {
    id: "GJK-1015",
    title: "Ankesë e dyfishtë për gropë",
    description:
      "E njëjta gropë që u raportua më herët në Nënë Tereza. Foto e re nga këndi tjetër.",
    date: "2026-09-25",
    time: "18:02",
    createdAt: "2026-09-25T18:02:00",
    location: loc("Rr. Nënë Tereza", "Qendër", 42.3802, 20.4305),
    category: "Infrastrukturë",
    directorateId: "INF",
    sector: "Mirëmbajtja e rrugëve",
    priority: "E lartë",
    status: "NE_SHQYRTIM",
    photoUrl: "https://picsum.photos/seed/gjk1015/800/500",
    aiAnalysis: ai(
      72,
      "Infrastrukturë",
      "E lartë",
      "INF",
      "Mundësi e lartë për duplikat të GJK-1031. Lokacioni dhe kategoria përputhen.",
    ),
    timeline: ["Raportuar", "Analizuar nga AI", "Në shqyrtim"],
    citizenName: "Petrit Rama",
  },
  {
    id: "GJK-1008",
    title: "Raport i pavlefshëm",
    description: "Tekst i paqartë pa lokacion konkret dhe pa foto të problemit.",
    date: "2026-09-21",
    time: "12:00",
    createdAt: "2026-09-21T12:00:00",
    location: loc("I papërcaktuar", "—", 42.3806, 20.4312),
    category: "Infrastrukturë",
    directorateId: "INF",
    sector: "Mirëmbajtja e rrugëve",
    priority: "E ulët",
    status: "REFUZUAR",
    photoUrl: "https://picsum.photos/seed/gjk1008/800/500",
    aiAnalysis: ai(
      31,
      "Infrastrukturë",
      "E ulët",
      "INF",
      "Raporti nuk përmban të dhëna të mjaftueshme për identifikimin e problemit.",
    ),
    timeline: ["Raportuar", "Analizuar nga AI", "Në shqyrtim"],
    citizenName: "Qytetar anonim",
    rejectionReason: "Foto e paqartë dhe mungon lokacioni konkret.",
  },
  {
    id: "GJK-1071",
    title: "Ankesë për orarin e zyrave",
    description:
      "Zyra e pranimit të dokumenteve mbyll më herët se orari i publikuar.",
    date: "2026-09-26",
    time: "10:05",
    createdAt: "2026-09-26T10:05:00",
    location: loc("Ndërtesa e Komunës", "Qendër", 42.3804, 20.4301),
    category: "Arsim",
    directorateId: "ADM",
    sector: "Administratë",
    priority: "E ulët",
    status: "DERGUAR_TE_DREJTORIA",
    directorateStatus: "NEW",
    verifiedBy: "Arta Krasniqi",
    photoUrl: "https://picsum.photos/seed/gjk1071/800/500",
    aiAnalysis: ai(
      70,
      "Arsim",
      "E ulët",
      "ADM",
      "Ankesë administrative për orarin e shërbimit. Drejtoria e Administratës.",
    ),
    timeline: [
      "Raportuar",
      "Analizuar nga AI",
      "Verifikuar nga Arkivisti",
      "Dërguar te Drejtoria",
    ],
    citizenName: "Luljeta Berisha",
  },
  {
    id: "GJK-1075",
    title: "Inspektim për ndërtim pa leje",
    description:
      "Po ndërtohet një shtesë pa leje në lagjen Brekoc. Qytetarët kërkojnë inspektim.",
    date: "2026-09-20",
    time: "09:40",
    createdAt: "2026-09-20T09:40:00",
    location: loc("Lagja Brekoc", "Brekoc", 42.3755, 20.425),
    category: "Ambient",
    directorateId: "INS",
    sector: "Inspektime",
    priority: "E lartë",
    status: "DERGUAR_TE_DREJTORIA",
    directorateStatus: "ACCEPTED",
    verifiedBy: "Arta Krasniqi",
    photoUrl: "https://picsum.photos/seed/gjk1075/800/500",
    aiAnalysis: ai(
      87,
      "Ambient",
      "E lartë",
      "INS",
      "Sinjal për ndërtim të dyshimtë. Drejtoria për Inspektime duhet të verifikojë lejen.",
    ),
    timeline: [
      "Raportuar",
      "Analizuar nga AI",
      "Verifikuar nga Arkivisti",
      "Dërguar te Drejtoria",
      "Në proces",
    ],
    citizenName: "Qytetar anonim",
  },
];

export const mockNotifications = [
  {
    id: "n1",
    text: "3 raporte të reja presin shqyrtim",
    time: "2 min më parë",
    unread: true,
  },
  {
    id: "n2",
    text: "GJK-1042 ka prioritet kritik",
    time: "18 min më parë",
    unread: true,
  },
  {
    id: "n3",
    text: "GJK-1028 u dërgua te drejtoria",
    time: "1 orë më parë",
    unread: false,
  },
];
